### ISSUE TITLE
Install request: xmds

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#13]
Not on new Legion. IN00777097

http://www.xmds.org/

**Comment by ikirker** [comment]
oh gods noooooooooooooooo

![psrqhtu](https://cloud.githubusercontent.com/assets/479061/10540613/6dfd5268-7401-11e5-9a7f-9376c0df7420.gif)

**Comment by GDagvadorj** [comment]
It seems that XMDS is not working on new legion. I have been installed it in my home directory on old legion (via Ian's script which installs xmds in my home directory) but now I could not submit jobs in old legion while could not compile my codes in new legion. What is the best way to resolve the problem? Also are you planning to install XMDS on the whole system?

Thanks in advance

G

**Comment by heatherkellyucl** [comment]
@GDagvadorj If you email your username to rc-support@ucl.ac.uk I can add you to the list of people who can still submit jobs on old Legion. The XMDS install scripts need to be redone for new Legion.

**Comment by owainkenwayucl** [comment]
OK - I'll take a look at this.

**Comment by owainkenwayucl** [comment]
@GDagvadorj: I've made an attempt at an install which you should be able to get to from the module xmds/2.2.2

You will need to run xmds2-setup to configure it.
Or you can run create-svn-xmds-inst to create an svn version in your home directory.

Can you test it and tell me if it's working for you?

**Comment by owainkenwayucl** [comment]
I've made a go of it but it's a bit of a mess.

I've informed the user and asked them to test it.

**Comment by owainkenwayucl** [comment]
OK, it's not working for me.

So hmm.

**Comment by owainkenwayucl** [comment]
Quick update.

The version from that module now mostly works, except that it's failing two of the unit tests with segfaults.

The script for installing the SVN version also works, although the version from SVN is failing three tests - the two that are failing for 2.2.2 and an extra one which is producing results outside of the expected range.

**Comment by owainkenwayucl** [comment]
@GDagvadorj:  It now almost entirely works.

I decided that since the seg faults in the failed tests were within OpenMPI's code, I'd switch to using the Intel MPI, with the GNU compilers.  This is a slightly odd configuration but the only mix of compilers+MPI on the system that works.

As a result the xmds/2.2.2 module now works, and requires that you have loaded:

python2/recommended 
compilers/gnu/4.9.2 
mpi/intel/2015/update3/gnu-4.9.2 
fftw/3.3.4-impi/gnu-4.9.2 
hdf/5-1.8.15/gnu-4.9.2

This version passes all the tests that aren't automatically skipped by run_tests.py.

You should re-run xmds2-setup.  This will import the new settings.  It will also restrict the compiler to -O2, needed to pass some of the tests.

It also includes the create-svn-xmds-inst script updated to work on the new OS.

*WARNING* Currently, the SVN version of XMDS always fails the following single test:

```
======================================================================
FAIL: test_nonlocal_access_multiple_components (__main__.ScriptTestCase)
geometry/nonlocal_access_multiple_components.xmds
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./run_tests.py", line 247, in newfunc
    return func(*(args + fargs), **newkeywords)
  File "./run_tests.py", line 235, in scriptTestingFunction
    "Dependent variable '%s' in moment group %i of file '%s' failed to pass tolerance criteria." % (v1['name'], mgNum+1, sourceFile))
AssertionError: Dependent variable 'phiaOut' in moment group 1 of file 'nonlocal_access_multiple_components.xsil' failed to pass tolerance criteria.

----------------------------------------------------------------------
```

It fails this regardless of compiler/options etc.

Good luck.

@heatherkellyucl: can you pass this on to the other users who have requested it?

**Comment by GDagvadorj** [comment]
Do we need to unload default compilers before load compilers/gnu/4.9.2?

**Comment by heatherkellyucl** [comment]
@GDagvadorj Yes - starting from the default modules you should do this:

```
module unload compilers
module load python2/recommended
module load compilers/gnu/4.9.2
module load mpi/intel/2015/update3/gnu-4.9.2
module load fftw/3.3.4-impi/gnu-4.9.2
module load hdf/5-1.8.15/gnu-4.9.2
module load xmds/2.2.2
```

**Comment by GDagvadorj** [comment]
The module 'mpi/intel/2015/update3/gnu-4.9.2' conflicts with the default module 'mpi/intel/2015/update3/intel'

**Comment by heatherkellyucl** [comment]
I missed one out - unload compilers and mpi.

**Comment by GDagvadorj** [comment]
Here is the my test job script:

#!/bin/bash -l
#$ -S /bin/bash

#$ -l h_rt=00:05:00
#$ -l mem=1G    
#$ -l tmpfs=15G 
#$ -N test_xmds_scripts
#$ -pe openmpi 12
#$ -cwd         
#$ -ac allow="Y"

module unload compilers
module unload mpi
module load python2/recommended
module load compilers/gnu/4.9.2
module load mpi/intel/2015/update3/gnu-4.9.2
module load fftw/3.3.4-impi/gnu-4.9.2
module load hdf/5-1.8.15/gnu-4.9.2
module load xmds/2.2.2

gerun ./gpe_opo_spinor_homogeneous --FPmp=1.1

But when I submit I got error:

'Unable to run job: job rejected: the requested parallel environment "openmpi" does not exist'

It seems I am calling wrong environment

**Comment by heatherkellyucl** [comment]
Look at https://wiki.rc.ucl.ac.uk/wiki/Accessing_the_new_OS_pilot for the jobscript changes on new Legion. (The main example scripts page is updated too now https://wiki.rc.ucl.ac.uk/wiki/Legion_Scripts).

You need to change `openmpi` to `mpi`. You can also probably remove the `#$ -ac allow="Y"`so it can run on any node, but you can test that to see if it works.

**Comment by GDagvadorj** [comment]
What is it?
qsub test.sh
'Unable to run job: job rejected: the requested project "LegacyUsers" does not exist'

**Comment by heatherkellyucl** [comment]
This is what I mentioned in the email I sent you - you need to rename or delete the `~/.sge_request` file. It is setting your project to LegacyUsers for old Legion.

**Comment by GDagvadorj** [comment]
I see. Thanks but I am running some jobs on old legion so need to wait to finish them.

**Comment by heatherkellyucl** [comment]
Alternatively, put `#$ -P AllUsers` in your script on new Legion, to set it to the normal default project.

**Comment by GDagvadorj** [comment]
Hi, 

Since my jobs finished on old Legion I am moving to new Legion but I got problem. Please have a look into "/scratch/scratch/ucapgda/BKT/SourceCode/XMDS/Tests" where you will see my test xmds codes and job script and what I got after submit the job. Please also not the path to the working directory which is not /Scratch. What it could be? 

Thanks in advance.

Galaa

**Comment by GDagvadorj** [comment]
Hi,

Since my jobs finished on old Legion I am moving to new Legion but I got problem. Please have a look into "/scratch/scratch/ucapgda/BKT/SourceCode/XMDS/Tests" where you will see my test xmds codes and job script and what I got after submit the job. Please also not the path to the working directory which is not /Scratch. What it could be?

Thanks in advance.

Galaa

On 2 Nov 2015, at 15:07, Dr Owain Kenway <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #13<https://github.com/UCL-RITS/rcps-buildscripts/issues/13>.

**Comment by heatherkellyucl** [comment]
The error you got was `APPLICATION TERMINATED WITH THE EXIT STRING: Illegal instruction (signal 4)`

Tested for AVX instructions:
```
find /scratch/scratch/ucapgda/BKT/SourceCode/XMDS/ -perm /111 -type f | xargs /shared/ucl/apps/rcops_scripts/hasavx -q
/scratch/scratch/ucapgda/BKT/SourceCode/XMDS/Tests/gpe: has AVX instructions
/scratch/scratch/ucapgda/BKT/SourceCode/XMDS/Tests/sgpe: has AVX instructions
```

The login nodes have AVX and the XYZ node types don't. So you can compile your XMDS code on a node of that type (inside a jobscript or interactively via qrsh if it takes 2hrs or less) or if you want your code to be able to use AVX instructions, you can only run it on the U or T nodes, so you'd need to put `#$ -ac allow=UT` in your jobscript.

You may be able to tell XMDS to compile code using `CXXFLAGS=-march=nehalem` to tell it what architecture to compile for - the xmds2-setup script already sets that, though.

**Comment by heatherkellyucl** [comment]
http://sourceforge.net/p/xmds/mailman/message/34349912/ 

`xmds2 --verbose` will show you what flags the compiler used. 

> The --verbose (or -g) option will list the compile and
link commands used by xmds2, so you can just copy and paste those lines and
add compiler options as you choose.

>If you want to add the compiler flags permanently, you can do, for example
`CXXFLAGS="-Wno-overflow, -Wstrict-aliasing" xmds2 --reconfigure`
where CXXFLAGS is a comma-separated list of options.

So that's where you'd want to pass `-march=nehalem`

This is where it gets them by default:
> You can find the code that decides what compilation flags to use for
various OSes and architectures in the xpdeint/support/wscript file.

That file is in `/shared/ucl/apps/xmds/2.2.2/gnu-4.9.2/xmds-2.2.2/xpdeint/support/wscript` and has this:
```
 if conf.env['CXX_NAME'] == 'gcc':
            machine_optimisations = [
                {
                    "msg": "Trying to make compiler optimise for this machine",
                    "cxxflags": "-march=native",
                },
                {
                    "msg": "Checking for Altivec",
                    "cxxflags": ['-mpim-altivec', '-maltivec'],
                },
                {
                    "msg": "Checking for AVX",
                    "cxxflags": ["-mavx", "-msse3", "-msse2", "-msse", "-mfpmath=sse"],
                },
                {
                    "msg": "Checking for SSE3",
                    "cxxflags": ["-msse3", "-msse2", "-msse", "-mfpmath=sse"],
                },
                {
                    "msg": "Checking for SSE2",
                    "cxxflags": ["-msse2", "-msse", "-mfpmath=sse"],
                },
                {
                    "msg": "Checking for SSE",
                    "cxxflags": ["-msse", "-mfpmath=sse"]
                }
            ]
```

**Comment by GDagvadorj** [comment]
So you mean that I have to run following command?:
CXXFLAGS=-march=nehalem xmds2 --reconfigure

**Comment by heatherkellyucl** [comment]
If the above is correct, yes. That should give you binaries that can run on any node type, but won't use AVX even if the node has it. You can run the `hasavx` test I mention above yourself after recompiling to check.

**Comment by GDagvadorj** [comment]
Hmmmmmm,

I have run above command, "CXXFLAGS=-march=nehalem xmds2 --reconfigure" but this command could not find parallel environments (MPI not found. No scripts using MPI can be compiled on this system). When I re-run the command xmds2-setup the config log saved to /home/ucapgda/.xmds/waf_configure/config.log. If I open this file I see "-march=nehalem -O2" at several places. But it does not change the file "/shared/ucl/apps/xmds/2.2.2/gnu-4.9.2/xmds-2.2.2/xpdeint/support/wscript" .

Also I have tried both other two options, compiling the codes in job scripts and submitting to U nodes, and both attempts failed. 

So what can I do now?

**Comment by heatherkellyucl** [comment]
When recompiling, you need to set things up the same way you would when compiling in the first place. So I assume you need to run xmds2-setup, then the reconfigure command. 

Nothing you do will change the wscript file - what you are trying to do here is override the settings in it.

**Comment by GDagvadorj** [comment]
I have submitted very short and 2 hours long test jobs again in the same place, "/scratch/scratch/ucapgda/BKT/SourceCode/XMDS/Tests". The short job successfully completed and other one running right now. The short job run on the node-t00a-001 and longer job is running on the node-u05a-004. But I do not know what class of these nodes. Also I have submitted 24 hours long job and if it successful the installation test will end.

**Comment by heatherkellyucl** [comment]
You can tell the node type by the name now - node-t00a-001 is a T node and node-u05a-00 is a U node. It should work on those anyway. It was the X, Y and Z nodes that it would fail on if it still had AVX instructions.

You can run the hasavx tool in your directory and it will tell you if anything in there still has AVX instructions:
```
find /scratch/scratch/ucapgda/BKT/SourceCode/XMDS/ -perm /111 -type f | xargs /shared/ucl/apps/rcops_scripts/hasavx -q
```

**Comment by GDagvadorj** [comment]
Yes, I run the command and got all my executable files have AVX instructions. Therefore, I tried to compile the code inside the job script (just adding a new line "xmds2 gee.xmds" have look at the sub-directory called Test_XYZ-nodes) since it does not take more than a minute. But it seems there is some error occurring when it compile, please have a look at the test_xmds.e*.

Since now we do not need to specify which node we want to run the job, for me the best solution is compile code using CXXFLAGS=-march=nehalem. when I compile code with --verbose I see both options "-march=nehalem" and "-march=native" in the outputs on screen so not sure/not-understand which option used. I put all flags in to a file called flags

**Comment by heatherkellyucl** [comment]
The error in your output file is 
```
  File "/shared/ucl/apps/xmds/2.2.2/gnu-4.9.2/xmds-2.2.2/xpdeint/parser2.py", line 430, in main
    "Ensure '%(xpdeintUserDataPath)s' exists and is writable." % locals()
KeyError: 'xpdeintUserDataPath'
```

The xpdeint source says that if you have the environment variable $XMDS_USER_DATA set, then it sets xpdeintUserDataPath to that, otherwise it tries to use ~/.xmds (which it can't write to from the compute nodes as that is not in Scratch).

Try putting this in your script (with whatever path you want, as long as it is in Scratch and exists):
```
export XMDS_USER_DATA=/scratch/scratch/ucapgda/somewhere
```

I'm not sure if it will expect the contents of your current ~/.xmds directory in there, or if it's ok to be blank to start with. If the above doesn't work, you could try moving your existing .xmds directory into Scratch, then creating a symlink in your home that points to it:
```
mv ~/.xmds /scratch/scratch/ucapgda/
ln -s /scratch/scratch/ucapgda/.xmds ~/.xmds
```

Then it will actually be in Scratch so can be written to, and your job should work.

You also appear to have a copy of wscript in that directory - I don't know if editing that to comment out the AVX options will have it use that instead of the central one.

**Comment by GDagvadorj** [comment]
When I implement first two suggestions, setting export and moving the .xmds directory to scratch, both attempts failed. The last one, editing the script in my directory, requires to re-run xmdx-setup which reset the old options. 

So for the moment best solution is to use only U and T nodes, but how busy these nodes compare to X and Y nodes? Tonight I may start submit data taking jobs.

**Comment by ikirker** [comment]
@GDagvadorj If you need anything else on this re-open, but otherwise closing due to inactivity.
