### ISSUE TITLE
Numpy 1.10.2 breaks LAPACK/BLAS detection for our build script.

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL-RITS/rcps-buildscripts#29]
If we try to run either the python 2 or python 3 bundle scripts, we get this error:

```none
Installing collected packages: numpy
  Running setup.py install for numpy
    Complete output from command /shared/ucl/apps/python/bundles/1451921561-3/venv/bin/python3.4 -c "import setuptools, tokenize;__file__='/tmp/pip-build-7yjz732n/numpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file
__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-5wekvzaj-record/install-record.txt --single-version-externally-managed --compile --install-headers /shared/ucl/apps/python/bundles/1451921561-3/venv/i
nclude/site/python3.4/numpy:
    blas_opt_info:
    blas_mkl_info:
      libraries mkl,vml,guide not found in ['/shared/ucl/apps/python/bundles/1451921561-3/venv/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
      NOT AVAILABLE

    openblas_info:
      libraries openblas not found in ['/shared/ucl/apps/python/bundles/1451921561-3/venv/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
      NOT AVAILABLE

    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas not found in ['/shared/ucl/apps/python/bundles/1451921561-3/venv/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64/sse2', '/usr/lib64', '/usr/lib/sse2', '/usr/lib', '/usr/lib/sse2', '/usr/lib/']
      NOT AVAILABLE

    atlas_3_10_blas_info:
      libraries satlas not found in ['/shared/ucl/apps/python/bundles/1451921561-3/venv/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64/sse2', '/usr/lib64', '/usr/lib/sse2', '/usr/lib', '/usr/lib/sse2', '/usr/lib/']
      NOT AVAILABLE

    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in ['/shared/ucl/apps/python/bundles/1451921561-3/venv/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64/sse2', '/usr/lib64', '/usr/lib/sse2', '/usr/lib', '/usr/lib/sse2', '/
usr/lib/']
      NOT AVAILABLE

    atlas_blas_info:
      libraries f77blas,cblas,atlas not found in ['/shared/ucl/apps/python/bundles/1451921561-3/venv/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64/sse2', '/usr/lib64', '/usr/lib/sse2', '/usr/lib', '/usr/lib/sse2', '/usr/
lib/']
      NOT AVAILABLE

    blas_info:
    Replacing _lib_names[0]=='blas' with 'openblas'
    Replacing _lib_names[0]=='openblas' with 'openblas'
    C compiler: cc

    creating /tmp/tmpxedlndus/tmp
    creating /tmp/tmpxedlndus/tmp/tmpxedlndus
    compile options: '-I/shared/ucl/apps/openblas/0.2.14/gnu-4.9.2/lib -I/usr/local/include -I/usr/include -I/shared/ucl/apps/python/bundles/1451921561-3/venv/include -c'
    cc: /tmp/tmpxedlndus/source.c
    cc /tmp/tmpxedlndus/tmp/tmpxedlndus/source.o -L/shared/ucl/apps/openblas/0.2.14/gnu-4.9.2/lib -lcblas -o /tmp/tmpxedlndus/a.out
    /bin/ld: cannot find -lcblas
    collect2: error: ld returned 1 exit status
    /bin/ld: cannot find -lcblas
    collect2: error: ld returned 1 exit status
    cc /tmp/tmpxedlndus/tmp/tmpxedlndus/source.o -L/shared/ucl/apps/openblas/0.2.14/gnu-4.9.2/lib -lblas -o /tmp/tmpxedlndus/a.out
    /bin/ld: cannot find -lblas
    collect2: error: ld returned 1 exit status
    Running from numpy source directory.
    /tmp/pip-build-7yjz732n/numpy/numpy/distutils/system_info.py:1651: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.__doc__)
    Traceback (most recent call last):
      File "/shared/ucl/apps/python/3.4.3/gnu-4.9.2/lib/python3.4/distutils/unixccompiler.py", line 194, in link
        self.spawn(linker + ld_args)
      File "/tmp/pip-build-7yjz732n/numpy/numpy/distutils/ccompiler.py", line 28, in <lambda>
        m = lambda self, *args, **kw: func(self, *args, **kw)
      File "/tmp/pip-build-7yjz732n/numpy/numpy/distutils/ccompiler.py", line 72, in CCompiler_spawn
        raise DistutilsExecError('Command "%s" failed with exit status %d%s' % (cmd, s, msg))
    distutils.errors.DistutilsExecError: Command "cc /tmp/tmpxedlndus/tmp/tmpxedlndus/source.o -L/shared/ucl/apps/openblas/0.2.14/gnu-4.9.2/lib -lcblas -o /tmp/tmpxedlndus/a.out" failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/pip-build-7yjz732n/numpy/numpy/distutils/system_info.py", line 1727, in has_cblas
        extra_postargs=info.get('extra_link_args', []))
      File "/shared/ucl/apps/python/3.4.3/gnu-4.9.2/lib/python3.4/distutils/ccompiler.py", line 734, in link_executable
        debug, extra_preargs, extra_postargs, None, target_lang)
      File "/shared/ucl/apps/python/3.4.3/gnu-4.9.2/lib/python3.4/distutils/unixccompiler.py", line 196, in link
        raise LinkError(msg)
    distutils.errors.LinkError: Command "cc /tmp/tmpxedlndus/tmp/tmpxedlndus/source.o -L/shared/ucl/apps/openblas/0.2.14/gnu-4.9.2/lib -lcblas -o /tmp/tmpxedlndus/a.out" failed with exit status 1

    During handling of the above exception, another exception occurred:
...
```

Followed by attempts to link against various blas lib names (-lblas etc) all of which fail.

This is despite us explicitly setting $LAPACK and $BLAS to the path to our openblas .so file.

Switching back to Numpy 1.9.2 resolves this issue, but obviously this is not sustainable, so a solution needs to be found.  Ominously, the readme for 1.10.2 states:

> * gh-6675 Optimized blas detection broken in master and 1.10.

http://sourceforge.net/projects/numpy/files/NumPy/1.10.2/

Which implies they tried to fix it and have broken it for us or that for some reason it is still broken for us.  The error suggests that it's not searching for BLAS in the path we've set as it's searching in '/shared/ucl/apps/python/bundles/1451921561-3/venv/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/'].

And we have set $BLAS/$LAPACK thus:

```bash
LAPACK=${LAPACK:-/shared/ucl/apps/openblas/0.2.14/gnu-4.9.2/lib/libopenblas.so}
BLAS=${BLAS:-/shared/ucl/apps/openblas/0.2.14/gnu-4.9.2/lib/libopenblas.so}

export LAPACK
export BLAS
```

There are various options for fixing this, one of which might be to create sym-links in the openblas lib directory to libopenblas.so called "libblas.so" and "liblapack.so".

**Comment by jenshnielsen** [comment]
I would suggest customising it with a site.cfg file to get the config that you want https://github.com/numpy/numpy/blob/master/site.cfg.example

**Comment by owainkenwayucl** [comment]
That might work if there's a sane way to pass it through pip.  I suspect any solution will have to stop us treating numpy like "any other" python package.  Which is quite annoying.

**Comment by jenshnielsen** [comment]
Looking at the example it claims to read ~/.numpy-site.cfg  when pip/easy_installing but I have not tested it.

**Comment by owainkenwayucl** [comment]
Actually, looking at the error, it's fairly clearly a bug. 

```none
    blas_info:
    Replacing _lib_names[0]=='blas' with 'openblas'
    Replacing _lib_names[0]=='openblas' with 'openblas'
```

Followed later on by attempts to link with -lblas, -cblas etc. rather than -lopenblas.

So I'm not convinced site.cfg would work.  

Will give it a shot though.

**Comment by owainkenwayucl** [comment]
If it tried to link with -lopenblas it would work because it picks up the right path from $LD_RUN_PATH

```none
distutils.errors.LinkError: Command "cc /tmp/tmpxedlndus/tmp/tmpxedlndus/source.o -L/shared/ucl/apps/openblas/0.2.14/gnu-4.9.2/lib -lcblas -o /tmp/tmpxedlndus/a.out" failed with exit status 1
```

**Comment by jenshnielsen** [comment]
It's sounds like a bug. As far as I can see it does not find either of openblas/atlas/MKL which should normally link to the internal (slow) blas implementation

**Comment by owainkenwayucl** [comment]
It might make some other things easier if I go the sym-link route actually.

*makes a face*

**Comment by owainkenwayucl** [comment]
I've gone the sym-link route.  I've put it into the openblas script, and am applying it in the four affected installs by hand.

**Comment by owainkenwayucl** [comment]
Right.  Done, closing.

**Comment by thvasilo** [comment]
Noting that I'm getting the same when trying to install in a virtualenv. 1.9.3 works.

**Comment by owainkenwayucl** [comment]
@thvasilo Hi - thanks for that - are you having this problem using our scripts or just installing numpy by itself?

**Comment by thvasilo** [comment]
@owainkenwayucl It happens when installing numpy by itself, so I realize now that this is wrong place to report this :/

**Comment by owainkenwayucl** [comment]
That's OK :)
