### ISSUE TITLE
Install Request: Python 3.8.x + package set.

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL-RITS/rcps-buildscripts#313]
Application: Python version 3.8.0

Cluster: All

Need to start the python 3.7 -> 3.8 treadmill.

 - [x] - Python 3.8.x interpreter
 - [x] - Partial package set
 - [x] - Full package set
 - [x] - Communicate with users
 - [x] - Make default

**Comment by owainkenwayucl** [comment]
Python 3.8.0 installed.

Package set fails at pysam (I know this tune).

**Comment by owainkenwayucl** [comment]
```
diff python-shared.list python-shared38-fixed.list
1,2d0
< pysam
< pysamstats
17d14
< cvxopt
44d40
< cyvcf2
```

It's now failing to install numba because there's no wheel for llvmlite.

I think this may have to wait until python 3.8.x is more mature...

**Comment by owainkenwayucl** [comment]
Now matplotlib is broken.

I think I'm going to leave this a few weeks.

**Comment by owainkenwayucl** [comment]
Matplotlib is broken because part of Python 3.8.0 can't see that it has os.link.

```
    ERROR: Command errored out with exit status 1:
     command: /lustre/shared/ucl/apps/python/bundles/1571736390-38/venv/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zyqbuvj8/matplotlib/setup.py'"'"'; __file__=
uvj8/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --eg
qbuvj8/matplotlib/pip-egg-info
         cwd: /tmp/pip-install-zyqbuvj8/matplotlib/
    Complete output (33 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zyqbuvj8/matplotlib/setup.py", line 232, in <module>
        result = package.check()
      File "/tmp/pip-install-zyqbuvj8/matplotlib/setupext.py", line 1089, in check
        import numpy
      File "/lustre/shared/ucl/apps/python/bundles/1571736390-38/venv/lib/python3.8/site-packages/numpy/__init__.py", line 142, in <module>
        from . import core
      File "/lustre/shared/ucl/apps/python/bundles/1571736390-38/venv/lib/python3.8/site-packages/numpy/core/__init__.py", line 17, in <module>
        from . import multiarray
      File "/lustre/shared/ucl/apps/python/bundles/1571736390-38/venv/lib/python3.8/site-packages/numpy/core/multiarray.py", line 14, in <module>
        from . import overrides
      File "/lustre/shared/ucl/apps/python/bundles/1571736390-38/venv/lib/python3.8/site-packages/numpy/core/overrides.py", line 9, in <module>
        from numpy.compat._inspect import getargspec
      File "/lustre/shared/ucl/apps/python/bundles/1571736390-38/venv/lib/python3.8/site-packages/numpy/compat/__init__.py", line 14, in <module>
        from . import py3k
      File "/lustre/shared/ucl/apps/python/bundles/1571736390-38/venv/lib/python3.8/site-packages/numpy/compat/py3k.py", line 16, in <module>
        from pathlib import Path, PurePath
      File "/shared/ucl/apps/python/3.8.0/gnu-4.9.2/lib/python3.8/pathlib.py", line 391, in <module>
        class _NormalAccessor(_Accessor):
      File "/shared/ucl/apps/python/3.8.0/gnu-4.9.2/lib/python3.8/pathlib.py", line 415, in _NormalAccessor
        link_to = os.link
    AttributeError: module 'os' has no attribute 'link'
    ============================================================================
    Edit setup.cfg to change the build options
    
    BUILDING MATPLOTLIB
                matplotlib: yes [2.2.4]
                    python: yes [3.8.0 (default, Oct 21 2019, 13:22:29)  [GCC
                            4.9.2]]
                  platform: yes [linux]
    
    REQUIRED DEPENDENCIES AND EXTENSIONS
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

It has os.link.

```
Myriad [login13] ~ :) > python3
Python 3.8.0 (default, Oct 21 2019, 13:22:29)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> test = os.link
>>> 

```

**Comment by owainkenwayucl** [comment]
OK, this seems to be due to matplotlib's setup.py deleting os.link, as found by the Sage math people: https://trac.sagemath.org/ticket/27754

This has been reported to the matplotlib people https://github.com/matplotlib/matplotlib/issues/14580 and there is a fix 2.2.5 when it's released.

Part of the problem is that pyfastaq wants an old (pre 3.0) version of matplotlib, so it may be better in future to move pyfastaq out of the python supported package set.

**Comment by owainkenwayucl** [comment]
OK, so we have a partial install, with a horrendous scipy hack: 

```
[rilakkuma:uccaoke] ~/S/r/lists ☻ ☛ diff python-3.list python-338-fixed.list
2,4d1
< numba
< boltztrap2
< multiqc
[rilakkuma:uccaoke] ~/S/r/lists ☹ ☛ 
diff python-shared.list python-shared38-fixed.list
1,2d0
< pysam
< pysamstats
17d14
< cvxopt
44d40
< cyvcf2
```

For proper install:

- [ ] - scipy wheel 
- [ ] - multiqc
- [ ] - pysam
- [ ] - pysamstats
- [ ] - cvxopt
- [ ] - cyvcf2

**Comment by owainkenwayucl** [comment]
Hy is also broken: 

```
Myriad [login13] ~ :) > module load python3/3.8
Myriad [login13] ~ :) > hy
Traceback (most recent call last):
  File "/shared/ucl/apps/python/bundles/python38-5.0.0/venv/bin/hy", line 5, in <module>
    from hy.cmdline import hy_main
  File "/lustre/shared/ucl/apps/python/bundles/1571741542-38/venv/lib/python3.8/site-packages/hy/cmdline.py", line 358, in <module>
    def koan_macro(ETname):
  File "/lustre/shared/ucl/apps/python/bundles/1571741542-38/venv/lib/python3.8/site-packages/hy/macros.py", line 55, in _
    fn = rename_function(fn, name)
  File "/lustre/shared/ucl/apps/python/bundles/1571741542-38/venv/lib/python3.8/site-packages/hy/_compat.py", line 69, in rename_function
    new_code = type(c)(*[getattr(c, 'co_{}'.format(a))
TypeError: an integer is required (got type bytes)

```

 - [ ] - Hy

**Comment by owainkenwayucl** [comment]
Reported Hy issue: https://github.com/hylang/hy/issues/1827

**Comment by owainkenwayucl** [comment]
Since deploying successfully on Myriad with the subset, something has changed which means scipy doesn't build on the other clusters...

```
...
setuptools/build_meta.py", line 236, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/shared/ucl/apps/python/3.8.0/gnu-4.9.2/lib/python3.8/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 505, in <module>
        setup_package()
      File "setup.py", line 481, in setup_package
        from numpy.distutils.core import setup
      File "/tmp/pip-build-env-ihist6_1/overlay/lib/python3.8/site-packages/numpy/__init__.py", line 142, in <module>
        from . import add_newdocs
      File "/tmp/pip-build-env-ihist6_1/overlay/lib/python3.8/site-packages/numpy/add_newdocs.py", line 13, in <module>
        from numpy.lib import add_newdoc
      File "/tmp/pip-build-env-ihist6_1/overlay/lib/python3.8/site-packages/numpy/lib/__init__.py", line 8, in <module>
        from .type_check import *
      File "/tmp/pip-build-env-ihist6_1/overlay/lib/python3.8/site-packages/numpy/lib/type_check.py", line 11, in <module>
        import numpy.core.numeric as _nx
      File "/tmp/pip-build-env-ihist6_1/overlay/lib/python3.8/site-packages/numpy/core/__init__.py", line 26, in <module>
        raise ImportError(msg)
    ImportError:
    Importing the multiarray numpy extension module failed.  Most
    likely you are trying to import a failed build of numpy.
    If you're working with a numpy git repo, try `git clean -xdf` (removes all
    files not under version control).  Otherwise reinstall numpy.
    
    Original error was: libgfortran-ed201abd.so.3.0.0: cannot open shared object file: No such file or directory
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/UCL/applications/python/bundles/1571747721-38/venv/bin/python3.8 /home/UCL/applications/python/bundles/1571747721-38/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpu7rxl0p2 Check the logs for full command output.
```

**Comment by owainkenwayucl** [comment]
Right - this is another sym-link issue.

**Comment by owainkenwayucl** [comment]
OK, we can't do OpenBlas the way I was doing it.

**Comment by owainkenwayucl** [comment]
I've installed OpenBLAS 0.3.7 for this.

**Comment by owainkenwayucl** [comment]
OK using our own OpenBLAS has solved the Scipy problem.

**Comment by owainkenwayucl** [comment]
Scipy will have wheels from 1.3.2: https://github.com/scipy/scipy/issues/10927

**Comment by owainkenwayucl** [comment]
Scipy 1.4.1 works on Python 3.8 - removed from `$PIPNOBIN`.

**Comment by owainkenwayucl** [comment]
As of now, everything works except cyvcf2

**Comment by owainkenwayucl** [comment]
It looks like cyvcf2 works now.

So I think I should build a new python 3.8 and update everything.

**Comment by owainkenwayucl** [comment]
The `python3/3.8` bundles now contain all supported packages and use Python 3.8.6.

**Comment by owainkenwayucl** [comment]
Next week: draft usual email saying we are changing the default, set the date for move to be start of 2021.

**Comment by owainkenwayucl** [comment]
Sent email - set upgrade for the 11th January - gives time for people to get back from Christmas leave etc.

**Comment by owainkenwayucl** [comment]
We actually made this change back in January as planned.

Closing issue.
