### ISSUE TITLE
Install fix: OpenMM 7.3.1 Python interfaces

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#456]
[IN:04813875]

Current error with the Python interfaces in our install:

```
Traceback (most recent call last):
  File "../test.py", line 1, in <module>
    from simtk.openmm.app import *
  File "/shared/ucl/apps/OpenMM/7.3.1/cpu/lib/python3.6/site-packages/simtk/openmm/__init__.py", line 19, in <module>
    from simtk.openmm.openmm import *
  File "/shared/ucl/apps/OpenMM/7.3.1/cpu/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 28, in <module>
    _openmm = swig_import_helper()
  File "/shared/ucl/apps/OpenMM/7.3.1/cpu/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 20, in swig_import_helper
    import _openmm
ImportError: No module named _openmm
``` 

Python interfaces seem broken since the import doesn't work.
This test should work:
`python -m simtk.testInstallation`

Our build used `make PythonInstall` - EasyBuild just uses setup.py directly.

```
preinstallopts = ' export OPENMM_INCLUDE_PATH=%(installdir)s/include && '
preinstallopts += ' export OPENMM_LIB_PATH=%(installdir)s/lib && '

# required to install the python API
installopts = ' && cd python && python setup.py build && python setup.py install --prefix=%(installdir)s'
```

Going to try an install in my home first that does this, see if the sanity check works, and if so, rerun the python API install part of the process for the existing installs (is separate from the main build).

**Comment by heatherkellyucl** [comment]
Same problem happens with the new build.

At some point this worked because Owain ran acceptance tests on Myriad and Kathleen: https://github.com/UCL-RITS/HPC-Acceptance-Tests/tree/master/Applications/OpenMM

The imports as written in those scripts fail now on both Kathleen and Myriad.

**Comment by heatherkellyucl** [comment]
No, it is ok.

I think there were two things going on here:

The user needs to make sure they call it with `python3` and not `python`. In my new install case, I was still inside the virtualenv used to do the install.
