### ISSUE TITLE
Install Request: PyTorch working CPU and GPU versions [IN05264867]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#485]
The currently installed version of PyTorch on Myriad no longer works. Running:
```
##!/bin/bash -l
#$ -l mem=16G
#$ -l h_rt=00:59:00

#$ -l gpu=1
#$ -S /bin/bash
#$ -j y
#$ -N job_20220317

#$ -cwd 

module load python3/3.7
module load cuda/10.0.130/gnu-4.9.2
module load cudnn/7.5.0.56/cuda-10.0
module load pytorch/1.2.0/gpu

python torch_test.py
```
fails with:
```
Traceback (most recent call last):
  File "torch_test.py", line 4, in <module>
    from torchvision import datasets
  File "/shared/ucl/apps/pytorch/1.2.0/python3.7.4/cuda/lib/python3.7/site-packages/torchvision/__init__.py", line 2, in <module>
    from torchvision import datasets
  File "/shared/ucl/apps/pytorch/1.2.0/python3.7.4/cuda/lib/python3.7/site-packages/torchvision/datasets/__init__.py", line 9, in <module>
    from .fakedata import FakeData
  File "/shared/ucl/apps/pytorch/1.2.0/python3.7.4/cuda/lib/python3.7/site-packages/torchvision/datasets/fakedata.py", line 3, in <module>
    from .. import transforms
  File "/shared/ucl/apps/pytorch/1.2.0/python3.7.4/cuda/lib/python3.7/site-packages/torchvision/transforms/__init__.py", line 1, in <module>
    from .transforms import *
  File "/shared/ucl/apps/pytorch/1.2.0/python3.7.4/cuda/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 17, in <module>
    from . import functional as F
  File "/shared/ucl/apps/pytorch/1.2.0/python3.7.4/cuda/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 5, in <module>
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/shared/ucl/apps/pytorch/1.2.0/python3.7.4/cuda/lib/python3.7/site-packages/PIL/__init__.py)
```
We need to install a newer working version eg current stable version 1.11.0

https://pytorch.org/get-started/locally/

**Comment by balston** [comment]
Note: GPU version will probably need to be built on a GPU node with correct CUDA modules loaded and access to the CUDA drivers.

**Comment by balston** [comment]
Updating build script for current stable version PyTorch 1.11.0 using CUDA 10.2 or CUDA 11.3. Note 10.2 is the oldest supported CUDA version.

**Comment by balston** [comment]
We don't have CUDA 10.2 on Myriad so will need to use 11.3 which according to the PyTorch documentation needs a slightly different pip3 command:
```
 pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
```

**Comment by balston** [comment]
CUDA version install job submitted:
```
cd ~ccspapp/Software/PyTorch
qsub build-cuda-1.11.0.sh

job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID
-----------------------------------------------------------------------------------------------------------------
9925155 2.84716 PyTorch-GP ccspapp      qw    05/19/2022 15:52:36                                    1
```

**Comment by balston** [comment]
The CUDA version install job ran overnight.

I'm now going to produce a module for each version and test.

**Comment by balston** [comment]
I've uploaded the 1.11.0 modules to my area on Myriad and have submitted a GPU version test job.

**Comment by balston** [comment]
I've now submitted a CPU version job as well.

**Comment by balston** [comment]
I've completely messed up the CPU version module file (I'm loading the wrong version of Python). Fixing and trying the test job again.

**Comment by balston** [comment]
OK CPU test job now works! I'm still waiting for the GPU test job to run.

**Comment by balston** [comment]
Looks like the GPU one has now worked as well.

**Comment by balston** [comment]
I'm pulling the modules onto Myriad for both the CPU and GPU versions. I will then run a pair of test jobs with the live modules.

**Comment by balston** [comment]
Successfully tested PyTorch 1.11.0 on Myriad:

- [ ] CPU version;
- [ ] GPU version.

**Comment by balston** [comment]
Module commands to use the CPU version are:
```
module -f unload compilers mpi gcc-libs
module load beta-modules
module load gcc-libs/10.2.0
module load python3/3.9-gnu-10.2.0
module load pytorch/1.11.0/cpu
```
and for the GPU version are:
```
module -f unload compilers mpi gcc-libs
module load beta-modules
module load gcc-libs/10.2.0
module load python3/3.9-gnu-10.2.0
module load cuda/11.3.1/gnu-10.2.0
module load cudnn/8.2.1.32/cuda-11.3
module load pytorch/1.11.0/gpu
```
An example job script for running the GPU version on Myriad is:
```
#!/bin/bash -l

# Batch script to run a PyTorch GPU job under SGE.

# Request a number of GPU cards, in this case 1
#$ -l gpu=1

# Request One hour of wallclock time (format hours:minutes:seconds).
#$ -l h_rt=1:0:0

# Request 16 gigabyte of RAM (must be an integer followed by M, G, or T)
#$ -l mem=16G

# Request 15 gigabyte of TMPDIR space (default is 10 GB)
#$ -l tmpfs=15G

# Set the name of the job.
#$ -N PyTorch_test

# Set the working directory to somewhere in your scratch space.
# Replace "<your_UCL_id>" with your UCL user ID :)
#$ -wd /home/<your_UCL_id>/Scratch/PyTorch_output

module -f unload compilers mpi gcc-libs
module load beta-modules
module load gcc-libs/10.2.0
module load python3/3.9-gnu-10.2.0
module load cuda/11.3.1/gnu-10.2.0
module load cudnn/8.2.1.32/cuda-11.3
module load pytorch/1.11.0/gpu

python torch_test.py
```

**Comment by balston** [comment]
I've emailed the original requester via their RF ticket. There was also another user wanting PyTorch. I need to find their RF ticket and respond.

**Comment by balston** [comment]
The other ticket is IN05311966 and @heatherkellyucl has emailed the user about PyTorch 1.11.0.

**Comment by balston** [comment]
PyTorch added to GPU and Myriad doc pages.

**Comment by balston** [comment]
PyTorch needs to be built on a GPU node so will submit the build as a free job.

**Comment by balston** [comment]
Build job submitted on Young for GPU version:
```
job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID
-----------------------------------------------------------------------------------------------------------------
 747381 0.00000 PyTorch-GP ccspapp      qw    09/08/2022 11:07:46                                    4
```

**Comment by balston** [comment]
Build completed without errors. Submitted a test job to see if PyTorch GPU version works:
```
job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID
-----------------------------------------------------------------------------------------------------------------
 747431 0.00000 PyTorch_te ccaabaa      qw    09/08/2022 12:03:17                                    4
```

**Comment by balston** [comment]
The CPU version of PyTorch 1.11.0 has also been built on Young and I've submitted a test job.

**Comment by balston** [comment]
Test job ran out of wallclock time so increased from 1 hour and resubmitted.

**Comment by balston** [comment]
Test CPU job worked on Young.

**Comment by balston** [comment]
User need an additional Python package that depends on PyTorch. This worked when done in a virtual env.
