### ISSUE TITLE
Install request: tmap R package with V8 javascript engine dependency

### ISSUE THREAD

**Issue by tcouch** [UCL-RITS/rcps-buildscripts#80]
An rstudio server user has requested an R package called tmap. Installation currently fails due to a missing library called V8 which is a javascript engine apparently. Some possibly helpful instructions on the V8 wiki: https://github.com/v8/v8/wiki/Building%20from%20Source

**Comment by tcouch** [comment]
Error message from package install process:
```
** package ‘V8’ successfully unpacked and MD5 sums checked
Using PKG_CFLAGS=-I/usr/include/v8-3.14
Using PKG_LIBS=-lv8
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because  was not found. Try installing:
 * deb: libv8-3.14-dev (formerly: libv8-dev) (Debian, Ubuntu)
 * rpm: v8-314-devel (formerly: v8-devel) (Fedora, EPEL)
 * brew: v8-315 (OSX) -- NOT regular v8! Tap from homebrew/versions
 * csw: libv8_dev (Solaris)
To use a custom libv8, set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘V8’
* removing ‘/nfs/rcs/home3/ccea/cceatco/R/x86_64-pc-linux-gnu-library/3.3/V8’
Warning in install.packages :
  installation of package ‘V8’ had non-zero exit status
```

**Comment by owainkenwayucl** [comment]
V8 is a google thing so it's _probably_ relatively easy to install.

**Comment by owainkenwayucl** [comment]
And then I looked at the install instructions.  DAMMIT GOOGLE.

**Comment by owainkenwayucl** [comment]
So it requires Google's own layer on top of git which only supports Python 2.

**Comment by owainkenwayucl** [comment]
I've put `depot_tools` on.

Next up v8.

**Comment by owainkenwayucl** [comment]
Right.  `v8` builds but it doesn't generate a shared library.  Scrutenising the total lack of documentation to work out what to do.  `d8` (the shell) works fine though.

**Comment by owainkenwayucl** [comment]
I had it working.  But now it's unworking and I've no idea why.

**Comment by owainkenwayucl** [comment]
I've installed v8 on Legion and Grace:

```
Legion [login08] ~ ☻ ➤ module load v8
Legion [login08] ~ ☻ ➤ d8
V8 version 5.6.326.55
d8> 
```

You'll need to have `depot_tools` loaded to build it if you want to built it somewhere else.

**Comment by owainkenwayucl** [comment]
(the approximate steps assuming modules and build scripts are up to date)

```
module load rcps-core
module load compilers/gnu
cd /shared/ucl/apps/build_scripts
./depot_tools-git_install
module load python/2.7.12
module load depot_tools
./v8-5.6_install
```

(I'm sure I've mised something)

**Comment by owainkenwayucl** [comment]
(where it may go wrong is if the revision of depot_tools is newer than the one in the module file - yay for doing stuff though git)

**Comment by tcouch** [comment]
Yep looks like depot_tools is newer in my case. Added /shared/ucl/apps/depot_tools/014cb03/depot_tools to PATH manually to run v8-5.6_install

Seems to be working...

**Comment by tcouch** [comment]
2 hours later it's done. Seems to work.

**Comment by tcouch** [comment]
```
* installing *source* package ‘V8’ ...
** package ‘V8’ successfully unpacked and MD5 sums checked
Using PKG_CFLAGS=-I/usr/include/v8-3.14
Using PKG_LIBS=-lv8
------------------------- ANTICONF ERROR ---------------------------
Oh dear. The wrong version of libv8 is installed on the system.
This package needs the 3.14 / 3.15 branch of libv8.
On Fedora try this:
  sudo yum remove v8-devel
  sudo yum install v8-314-devel
On MacOS Homebrew try this:
  brew remove v8
  brew install v8-315
To use a custom libv8 build set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
```

Dammit. Not sure if setting INCLUDE-DIR and LIB_DIR will work.

**Comment by owainkenwayucl** [comment]
OK, so theoretically, for other packages that don't change their build system every five minutes this would be easy.

Not sure about `v8` since it's had at least three build systems so I may have to start from scratch.  I'll give it a go and see what happens.

**Comment by owainkenwayucl** [comment]
Hmm.

Never mind the build system, it looks like `gclient sync` can't even check out the 3.15 dependencies.

```
Branch 3.15 set up to track remote ref refs/branch-heads/3.15.
Switched to a new branch '3.15'
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "http://gyp.googlecode.com/svn/trunk" "/shared/ucl/apps/v8/3.15/v8/build/_gclient_gyp_kX_wM1"' in /shared/ucl/apps/v8/3.15 failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "http://gyp.googlecode.com/svn/trunk" "/shared/ucl/apps/v8/3.15/v8/build/_gclient_gyp_kX_wM1"' in /shared/ucl/apps/v8/3.15 failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "http://gyp.googlecode.com/svn/trunk" "/shared/ucl/apps/v8/3.15/v8/build/_gclient_gyp_kX_wM1"' in /shared/ucl/apps/v8/3.15 failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "http://gyp.googlecode.com/svn/trunk" "/shared/ucl/apps/v8/3.15/v8/build/_gclient_gyp_kX_wM1"' in /shared/ucl/apps/v8/3.15 failed; will retry after a short nap...
Syncing projects: 100% ( 2/ 2) v8/build/gyp

v8/build/gyp (ERROR)
----------------------------------------
[0:00:00] Started.
[0:00:00] 

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress http://gyp.googlecode.com/svn/trunk /shared/ucl/apps/v8/3.15/v8/build/_gclient_gyp_kX_wM1' in '/shared/ucl/apps/v8/3.15'
[0:00:00] Cloning into '/shared/ucl/apps/v8/3.15/v8/build/_gclient_gyp_kX_wM1'...
[0:00:00] fatal: repository 'http://gyp.googlecode.com/svn/trunk/' not found

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress http://gyp.googlecode.com/svn/trunk /shared/ucl/apps/v8/3.15/v8/build/_gclient_gyp_kX_wM1' in '/shared/ucl/apps/v8/3.15'
[0:00:01] Cloning into '/shared/ucl/apps/v8/3.15/v8/build/_gclient_gyp_kX_wM1'...
[0:00:01] fatal: repository 'http://gyp.googlecode.com/svn/trunk/' not found

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress http://gyp.googlecode.com/svn/trunk /shared/ucl/apps/v8/3.15/v8/build/_gclient_gyp_kX_wM1' in '/shared/ucl/apps/v8/3.15'
[0:00:02] Cloning into '/shared/ucl/apps/v8/3.15/v8/build/_gclient_gyp_kX_wM1'...
[0:00:02] fatal: repository 'http://gyp.googlecode.com/svn/trunk/' not found

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress http://gyp.googlecode.com/svn/trunk /shared/ucl/apps/v8/3.15/v8/build/_gclient_gyp_kX_wM1' in '/shared/ucl/apps/v8/3.15'
[0:00:04] Cloning into '/shared/ucl/apps/v8/3.15/v8/build/_gclient_gyp_kX_wM1'...
[0:00:04] fatal: repository 'http://gyp.googlecode.com/svn/trunk/' not found
Traceback (most recent call last):
  File "/shared/ucl/apps/depot_tools/c03a9cf/depot_tools/gclient_scm.py", line 881, in _Clone
    self._Run(clone_cmd, options, cwd=self._root_dir, retry=True)
  File "/shared/ucl/apps/depot_tools/c03a9cf/depot_tools/gclient_scm.py", line 1166, in _Run
    gclient_utils.CheckCallAndFilterAndHeader(cmd, env=env, **kwargs)
  File "/shared/ucl/apps/depot_tools/c03a9cf/depot_tools/gclient_utils.py", line 303, in CheckCallAndFilterAndHeader
    return CheckCallAndFilter(args, **kwargs)
  File "/shared/ucl/apps/depot_tools/c03a9cf/depot_tools/gclient_utils.py", line 549, in CheckCallAndFilter
    rv, args, kwargs.get('cwd', None), None, None)
CalledProcessError: Command 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress http://gyp.googlecode.com/svn/trunk /shared/ucl/apps/v8/3.15/v8/build/_gclient_gyp_kX_wM1' returned non-zero exit status 128 in /shared/ucl/apps/v8/3.15
----------------------------------------
Traceback (most recent call last):
  File "/shared/ucl/apps/depot_tools/c03a9cf/depot_tools/gclient.py", line 2128, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/shared/ucl/apps/depot_tools/c03a9cf/depot_tools/gclient.py", line 2114, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/shared/ucl/apps/depot_tools/c03a9cf/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/shared/ucl/apps/depot_tools/c03a9cf/depot_tools/gclient.py", line 1876, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/shared/ucl/apps/depot_tools/c03a9cf/depot_tools/gclient.py", line 1363, in RunOnDeps
    work_queue.flush(revision_overrides, command, args, options=self._options)
  File "/shared/ucl/apps/depot_tools/c03a9cf/depot_tools/gclient_utils.py", line 1048, in run
    self.item.run(*self.args, **self.kwargs)
  File "/shared/ucl/apps/depot_tools/c03a9cf/depot_tools/gclient.py", line 772, in run
    file_list)
  File "/shared/ucl/apps/depot_tools/c03a9cf/depot_tools/gclient_scm.py", line 156, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "/shared/ucl/apps/depot_tools/c03a9cf/depot_tools/gclient_scm.py", line 417, in update
    self._Clone(revision, url, options)
  File "/shared/ucl/apps/depot_tools/c03a9cf/depot_tools/gclient_scm.py", line 889, in _Clone
    if os.listdir(tmp_dir):
OSError: [Errno 2] No such file or directory: '/shared/ucl/apps/v8/3.15/v8/build/_gclient_gyp_kX_wM1'
```

**Comment by owainkenwayucl** [comment]
Right.

It looks like I'll need to patch in the new GYP repo (https://chromium.googlesource.com/external/gyp) so I guess I should really start a new build script that uses gyp to build.

Oh well.

**Comment by owainkenwayucl** [comment]
OK - I'm now at the stage where it builds the d8 shell, but not the library.

**Comment by owainkenwayucl** [comment]
It's built properly in a home directory - now deploying to Legion and Grace.

**Comment by owainkenwayucl** [comment]
OK - on the RStudio server you need to do:

**Comment by owainkenwayucl** [comment]
```
Grace [login01] ~ ☻ ➤ module load v8/3.15
Grace [login01] ~ ☻ ➤ d8
V8 version 3.15.11.18 [console: dumb]
d8> 
```

**Comment by tcouch** [comment]
Ran into some difficulties getting R to build the V8 package. When building V8 R sets PKG_CFLAGS and PKG_LIBS to two non-existent directories. To fix this, I passed the lib and include dirs as arguments to install.packages.
```
export CONFIG_VARS='INCLUDE_DIR=/shared/ucl/apps/v8/3.15/v8/include LIB_DIR=/shared/ucl/apps/v8/3.15/v8/out/x64.release/lib.target'
```
```
configVars <- Sys.getenv("CONFIG_VARS")
install.packages (V8, lib=mainLib, repos=repros, configure.vars=configVars);
```

Installing tmap package  then completes succesfully and loads successfully.
Not sure how to add this in to the current process for building all the other R packages.

**Comment by tcouch** [comment]
Possible solution?
https://github.com/tcouch/rcps-buildscripts/commit/15e712ab1961fb40dbb825b9ad3b910c5f685410

**Comment by owainkenwayucl** [comment]
I guess maybe we should bring this into the main build scripts when you have it working?

**Comment by tcouch** [comment]
This has been done and added to build scripts
